[package]
name = "spirvemu"
version = "0.1.0"
edition = "2024"

[lib]
name = "spirvemu"
path = "src/lib.rs"

[[bin]]
name = "spirvemubin"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
miette = "7.6.0"
num = "0.4.3"
rand = "0.10.2"
ratatui = "0.30.2"
rspirv = "0.13.0"

[dev-dependencies]
naga = { version = "30.0.0", features = ["spv-out", "wgsl-in"] }
test-case = "3.3.1"
